var pageObjects = {}

module.exports = {
    beforeEach: browser => {
        pageObjects = browser.page.yoodlizePO()
        pageObjects.navigate()
    },
    after: browser => {
        browser.end()
    },

    'Navigate Categories': browser => {
        pageObjects
            .click('@sAllTools')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Tools')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllOutdoor')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Outdoor')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllElectronics')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Electronics')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllParty')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Party')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllVehicles')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Vehicles')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllClothing')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Clothing')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllHome')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Home')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllToys')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Toys')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllLawn')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Lawn')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllSporting')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Sporting')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllBusiness')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Business')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllVenues')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Venues')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllExperts')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Experts')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllExperiences')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Experiences')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@sAllMisc')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Misc')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fTools')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Tools')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fOutdoor')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Outdoor')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fElectronics')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Electronics')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fParty')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Party')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fVehicles')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Vehicles')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fClothing')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Clothing')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(500)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fHome')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Home')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fToys')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Toys')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fLawn')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Lawn')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fSporting')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Sporting')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fBusiness')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Business')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fVenues')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Venues')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fExperts')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Experts')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fExperiences')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Experiences')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fMisc')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Misc')
        pageObjects
        .pause(100)
            .waitForElementVisible('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('._2oS_y._1BgQy.navbar-brand')
            .pause(100)
            .click('@fMusic')
            .pause(500)
            .useCss()
            .waitForElementVisible('.sc-jKVCRD.jSqgxr', 20000)
            .pause(100)
            .verify.containsText('.sc-jKVCRD.jSqgxr', 'Music')
    },
    'Search is available on all pages': browser => {
        pageObjects
            .waitForElementVisible('@navSearch')
            .pause(100)
            .verify.containsText('@navSearch', 'Search')
        pageObjects
        .pause(100)
            .click('@navWorks')
            .pause(100)
            .waitForElementVisible('@navSearch')
            .pause(100)
            .verify.containsText('@navSearch', 'Search')
        pageObjects
        .pause(100)
            .click('@navSearch')
            .pause(100)
            .waitForElementVisible('@navSearch')
            .pause(100)
        pageObjects
        .pause(100)
            .useXpath()
            .click('//*[text()="List an Item"]')
            .useCss()
            .pause(100)
            .waitForElementVisible('@navSearch')
            .pause(100)
            .verify.containsText('@navSearch', 'Search')
        pageObjects
        .pause(100)
            .useXpath()
            .click('//*[text()="Terms"]')
            .useCss()
            .pause(100)
            .waitForElementVisible('@navSearch')
            .pause(100)
            .verify.containsText('@navSearch', 'Search')
        pageObjects
        .pause(100)
            .useXpath()
            .click('//*[text()="Privacy"]')
            .useCss()
            .pause(100)
            .waitForElementVisible('@navSearch')
            .pause(100)
            .verify.containsText('@navSearch', 'Search')
        pageObjects
        .pause(100)
            .logIn('testing.yoodlize1@gmail.com')
            .useXpath() 
            .click('//*[text()="List Your Stuff"]')
            .useCss()
            .pause(100)
            .waitForElementVisible('@sSearch')
            .pause(100)
            pageObjects
            .useXpath()
            .click('//i[@class="fal fa-comments hidden-md hidden-lg hidden-xs"]')
            .useCss()
            .pause(100)
            .waitForElementVisible('@sSearch')
            .pause(100)
            pageObjects
            .useXpath()
            .click('(//*[text()="My Listings"])[2]')
            .useCss()
            .pause(100)
            .waitForElementVisible('@sSearch')
            .pause(100)
            pageObjects
            .useXpath()
            .click('(//*[text()="Reviews"])[2]')
            .useCss()
            .pause(100)
            .waitForElementVisible('@sSearch')
            .pause(100)
            pageObjects
            .useXpath()
            .click('(//*[text()="Profile"])[1]')
            .useCss()
            .pause(100)
            .waitForElementVisible('@sSearch')
            .pause(100)
            pageObjects
            .useXpath()
            .click('//*[text()="Account"]')
            .useCss()
            .pause(100)
            .waitForElementVisible('@sSearch')
            .pause(100)
    }
}