var pageObjects = {}

module.exports = {
    beforeEach: browser => {
        pageObjects = browser.page.yoodlizePO()
        pageObjects.navigate()
    },
    after: browser => {
        browser.end()
    },

    // 'Navigate Categories': browser => {
    //     pageObjects
    //         .click('@sAllTools')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Tools')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllOutdoor')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Outdoor')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllElectronics')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Electronics')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllParty')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Party')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllVehicles')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Vehicles')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllClothing')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Clothing')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllHome')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Home')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllToys')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Toys')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllLawn')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Lawn')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllSporting')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Sporting')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllBusiness')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Business')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllVenues')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Venues')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllExperts')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Experts')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllExperiences')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Experiences')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@sAllMisc')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Misc')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fTools')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Tools')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fOutdoor')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Outdoor')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fElectronics')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Electronics')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fParty')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Party')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fVehicles')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Vehicles')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fClothing')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Clothing')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fHome')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Home')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fToys')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Toys')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fLawn')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Lawn')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fSporting')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Sporting')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fBusiness')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Business')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fVenues')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Venues')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fExperts')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Experts')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fExperiences')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Experiences')
    //     pageObjects
    //         .waitForElementVisible('.navbar-brand')
    //         .click('.navbar-brand')
    //         .click('@fMisc')
    //         .pause(500)
    //         .useCss()
    //         .waitForElementVisible('.sc-kaNhvL')
    //         .verify.containsText('.sc-kaNhvL', 'Misc')
    // },
    'Search is available on all pages': browser => {
        pageObjects
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
        pageObjects
            .click('@navWorks')
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
        pageObjects
            .click('@navSearch')
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
        pageObjects
            .useXpath()
            .click('//*[text()="List an Item"]')
            .useCss()
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
        pageObjects
            .useXpath()
            .click('//*[text()="Terms"]')
            .useCss()
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
        pageObjects
            .useXpath()
            .click('//*[text()="Privacy"]')
            .useCss()
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
        pageObjects
            .logIn('testing.yoodlize1@gmail.com')
            .useXpath() 
            .click('//*[text()="List Your Stuff"]')
            .useCss()
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
            pageObjects
            .useXpath()
            .click('//*[text()="Inbox"]')
            .useCss()
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
            pageObjects
            .useXpath()
            .click('(//*[text()="My Listings"])[2]')
            .useCss()
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
            pageObjects
            .useXpath()
            .click('(//*[text()="Reviews"])[2]')
            .useCss()
            .waitForElementVisible('@navSearch')
            .verify.containsText('@navSearch', 'Search')
            pageObjects
            .useXpath()
            .click('(//*[text()="Profile"])[1]')


    }
}